package com.myapp.module;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_equipment", "id", Equipment.class);
		arp.addMapping("tb_kid", "id", Kid.class);
		arp.addMapping("tb_temp_record", "id", TempRecord.class);
		arp.addMapping("tb_tip", "id", Tip.class);
		arp.addMapping("tb_user", "id", User.class);
		arp.addMapping("tb_user_auth", "id", UserAuth.class);
	}
}

