package com.myapp.module;

import com.myapp.module.base.BaseSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subject extends BaseSubject<Subject> {
	public static final Subject dao = new Subject().dao();
}
