package com.myapp.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.String getUid() {
		return get("uid");
	}

	public M setRoleid(java.lang.String roleid) {
		set("roleid", roleid);
		return (M)this;
	}

	public java.lang.String getRoleid() {
		return get("roleid");
	}

	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public M setCreatedate(java.lang.String createdate) {
		set("createdate", createdate);
		return (M)this;
	}

	public java.lang.String getCreatedate() {
		return get("createdate");
	}

	public M setBase1(java.lang.String base1) {
		set("base1", base1);
		return (M)this;
	}

	public java.lang.String getBase1() {
		return get("base1");
	}

}
