package com.myapp.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserAuth<M extends BaseUserAuth<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public M setIdentityType(java.lang.String identityType) {
		set("identityType", identityType);
		return (M)this;
	}

	public java.lang.String getIdentityType() {
		return get("identityType");
	}

	public M setIdentifier(java.lang.String identifier) {
		set("identifier", identifier);
		return (M)this;
	}

	public java.lang.String getIdentifier() {
		return get("identifier");
	}

	public M setCredential(java.lang.String credential) {
		set("credential", credential);
		return (M)this;
	}

	public java.lang.String getCredential() {
		return get("credential");
	}

	public M setRegisterTime(java.util.Date registerTime) {
		set("registerTime", registerTime);
		return (M)this;
	}

	public java.util.Date getRegisterTime() {
		return get("registerTime");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}

	public java.lang.String getSalt() {
		return get("salt");
	}

	public M setVerified(java.lang.String verified) {
		set("verified", verified);
		return (M)this;
	}

	public java.lang.String getVerified() {
		return get("verified");
	}

}
