package com.myapp.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKid<M extends BaseKid<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public M setEquipid(java.lang.Integer equipid) {
		set("equipid", equipid);
		return (M)this;
	}

	public java.lang.Integer getEquipid() {
		return get("equipid");
	}

	public M setEquipnum(java.lang.String equipnum) {
		set("equipnum", equipnum);
		return (M)this;
	}

	public java.lang.String getEquipnum() {
		return get("equipnum");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public M setHeadurl(java.lang.String headurl) {
		set("headurl", headurl);
		return (M)this;
	}

	public java.lang.String getHeadurl() {
		return get("headurl");
	}

	public M setHealthIssue(java.lang.String healthIssue) {
		set("healthIssue", healthIssue);
		return (M)this;
	}

	public java.lang.String getHealthIssue() {
		return get("healthIssue");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public M setMaxtime(java.math.BigDecimal maxtime) {
		set("maxtime", maxtime);
		return (M)this;
	}

	public java.math.BigDecimal getMaxtime() {
		return get("maxtime");
	}

	public M setMintime(java.math.BigDecimal mintime) {
		set("mintime", mintime);
		return (M)this;
	}

	public java.math.BigDecimal getMintime() {
		return get("mintime");
	}

	public M setIsminalarm(java.lang.String isminalarm) {
		set("isminalarm", isminalarm);
		return (M)this;
	}

	public java.lang.String getIsminalarm() {
		return get("isminalarm");
	}

	public M setIsmaxalarm(java.lang.String ismaxalarm) {
		set("ismaxalarm", ismaxalarm);
		return (M)this;
	}

	public java.lang.String getIsmaxalarm() {
		return get("ismaxalarm");
	}

	public M setIsnotice(java.lang.String isnotice) {
		set("isnotice", isnotice);
		return (M)this;
	}

	public java.lang.String getIsnotice() {
		return get("isnotice");
	}

}
