package com.myapp.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTempRecord<M extends BaseTempRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setKidid(java.lang.Integer kidid) {
		set("kidid", kidid);
		return (M)this;
	}

	public java.lang.Integer getKidid() {
		return get("kidid");
	}

	public M setEquipid(java.lang.Integer equipid) {
		set("equipid", equipid);
		return (M)this;
	}

	public java.lang.Integer getEquipid() {
		return get("equipid");
	}

	public M setEquipnum(java.lang.String equipnum) {
		set("equipnum", equipnum);
		return (M)this;
	}

	public java.lang.String getEquipnum() {
		return get("equipnum");
	}

	public M setRecordTime(java.util.Date recordTime) {
		set("recordTime", recordTime);
		return (M)this;
	}

	public java.util.Date getRecordTime() {
		return get("recordTime");
	}

	public M setTemperature(java.math.BigDecimal temperature) {
		set("temperature", temperature);
		return (M)this;
	}

	public java.math.BigDecimal getTemperature() {
		return get("temperature");
	}

}
