package com.myapp.bean;

import com.myapp.bean.base.BaseEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equipment extends BaseEquipment<Equipment> {
	public static final Equipment dao = new Equipment().dao();
}
