package com.myapp.bean;

import com.myapp.bean.base.BaseKid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kid extends BaseKid<Kid> {
	public static final Kid dao = new Kid().dao();
}
