package com.myapp.bean;

import com.myapp.bean.base.BaseTempRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TempRecord extends BaseTempRecord<TempRecord> {
	public static final TempRecord dao = new TempRecord().dao();
}
