package com.myapp.bean;

import com.myapp.bean.base.BaseTip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tip extends BaseTip<Tip> {
	public static final Tip dao = new Tip().dao();
}
