package com.myapp.bean;

import com.myapp.bean.base.BaseUserAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAuth extends BaseUserAuth<UserAuth> {
	public static final UserAuth dao = new UserAuth().dao();
}
