package com.myapp.bean;

import java.util.List;

import com.myapp.bean.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public List<UserAuth> getUserAuth() {
		return UserAuth.dao.find("select * from tb_user_auth where userid = ? ", get("id"));
	}
}
